-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 21:34:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookflow` DEFAULT CHARACTER SET utf8 ;
USE `bookflow` ;

-- -----------------------------------------------------
-- Table `bookflow`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookflow`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `nomeFantasia` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookflow`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nomeAutor` VARCHAR(100) NOT NULL,
  `nomeEditora` VARCHAR(100) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `dataCadastro` DATE NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `fornecedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_fornecedor_idx` (`fornecedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_fornecedor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `bookflow`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookflow`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`usuario` (
  `id` INT NOT NULL,
  `userName` VARCHAR(50) NOT NULL,
  `senha` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookflow`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(8) NOT NULL,
  `hora` VARCHAR(8) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_venda_usuário1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `bookflow`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_usuário1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bookflow`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookflow`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`item_venda` (
  `livro_id` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `quantidadeItem` INT NOT NULL,
  `valorItem` DOUBLE NOT NULL,
  INDEX `fk_livro_has_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_livro_has_venda_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_venda_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `bookflow`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `bookflow`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
