-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 13:06:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookflow` DEFAULT CHARACTER SET utf8mb3 ;
USE `bookflow` ;

-- -----------------------------------------------------
-- Table `bookflow`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeAutor` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `biografia` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`editora` (
  `cnpj` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `nomeFantasia` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nomeAutor` VARCHAR(100) NOT NULL,
  `nomeEditora` VARCHAR(100) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `dataCadastro` DATE NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `fornecedor_id` INT NOT NULL,
  `editora_cnpj` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_fornecedor_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_livro_editora1_idx` (`editora_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_livro_fornecedor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `bookflow`.`fornecedor` (`id`),
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`editora_cnpj`)
    REFERENCES `bookflow`.`editora` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `senha` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(8) NOT NULL,
  `hora` VARCHAR(8) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_venda_usuário1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `bookflow`.`cliente` (`id`),
  CONSTRAINT `fk_venda_usuário1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bookflow`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`item_venda` (
  `livro_id` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `quantidadeItem` INT NOT NULL,
  `valorItem` DOUBLE NOT NULL,
  INDEX `fk_livro_has_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_livro_has_venda_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_venda_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `bookflow`.`livro` (`id`),
  CONSTRAINT `fk_livro_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `bookflow`.`venda` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`livro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`livro_autor` (
  `livro_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `bookflow`.`autor` (`id`),
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `bookflow`.`livro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bookflow`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookflow`.`logs` (
  `idlogs` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `tabela` VARCHAR(50) NOT NULL,
  `acao` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `dadosAntigos` TEXT NULL DEFAULT NULL,
  `dadosNovos` TEXT NULL DEFAULT NULL,
  `dataHora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlogs`),
  INDEX `fk_logs_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_logs_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bookflow`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
